title: 'BitCamp: Creating a Song Recommendation Engine with Azure'
description: (Add Description Here)
template:
  name: bitcamp-learning-lab
  repo: azure-functions-template
before:
  - type: createPullRequest
    title: 'Week 0: Welcome to BitCamp!'
    body: new_issue.md
    head: bitcamp
  - type: updateBranchProtection
    enforce_admins: false
    required_pull_request_reviews:
      include_admins: false
steps:
  - title: 'Week 0: Fundamentals of JavaScript'
    description: (Add Description Here)
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: respond
        with: prerequisite.md
  - title: 'Week 0: Creating an Analog Clock'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 0: Creating an Analog Clock'
        body: prerequisite.md
        head: bitcamp1
  - title: 'Week 1: Downloading an IDE'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        body: ide.md
        head: bitcamp2
        title: 'Week 1: Downloading an IDE'
  - title: 'Week 1: Configuring Azure Functions'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 1: Configuring Azure Functions'
        body: azure.md
        head: bitcamp3
  - title: 'Week 1: Learning to Use Github'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 1: Learning to Use Github'
        body: github.md
        head: bitcamp4
  - title: 'Week 2: Parsing Multipart Data'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 2: Parsing Multipart Data'
        body: github.md
        head: bitcamp5
  - title: 'Week 2: Creating a Face API Endpoint'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 2: Creating a Face API Endpoint'
        body: endpoint.md
        head: bitcamp6
  - title: 'Week 2: Calling Face API (Parameters)'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 2: Calling Face API (Parameters)'
        body: params.md
        head: bitcamp7
  - title: 'Week 2: Calling Face API (Fetch)'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 2: Calling Face API (Fetch)'
        body: fetch.md
        head: bitcamp8
  - title: 'Week 2: Installing Dependencies'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 2: Installing Dependencies'
        body: dependencies.md
        head: bitcamp9
  - title: 'Week 3: Creating an HTML Page'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 3: Creating an HTML Page'
        body: html.md
        head: bitcamp10
  - title: 'Week 3: Displaying Emotion Data'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 3: Displaying Emotion Data'
        body: data.md
        head: bitcamp11
  - title: 'Week 4: Creating a Web App'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 4: Creating a Web App'
        body: app.md
        head: bitcamp12
  - title: 'Week 4: Making an API Controller'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 4: Making an API Controller'
        body: apicontroller.md
        head: bitcamp13
  - title: 'Week 4: Recommendation Parameters'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 4: Recommendation Parameters'
        body: recparams.md
        head: bitcamp14
  - title: 'Week 4: Recommendation Call (GET)'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 4: Recommendation Call (GET)'
        body: reccall.md
        head: bitcamp15
  - title: 'Week 4: Return Method (API Controller)'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 4: Return Method (API Controller)'
        body: return.md
        head: bitcamp16
  - title: 'Week 4: UI Controller'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 4: UI Controller'
        body: uicontroller.md
        head: bitcamp17
  - title: 'Week 4: App Controller'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 4: App Controller'
        body: appcontroller.md
        head: bitcamp18
  - title: 'Week 4: Event Listener (Final Step)'
    description: (Add Description Here)
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: createPullRequest
        title: 'Week 4: Event Listener (Final Step)'
        body: eventlistener.md
        head: bitcamp19
        
tags:
  - Azure
  - Spotify API
  - Bit Project
